# Generated by Django 5.1.3 on 2024-11-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=255)),
                ('tamaño', models.CharField(max_length=100)),
                ('sillas', models.CharField(max_length=100)),
                ('can_cliente', models.CharField(max_length=100)),
                ('nom_cliente', models.CharField(max_length=100)),
                ('orden', models.CharField(max_length=100)),
            ],
        ),
    ]
