# Generated by Django 5.1.3 on 2024-12-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesa_app', '0002_remove_mesa_can_cliente_remove_mesa_nom_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='codigo',
        ),
        migrations.AddField(
            model_name='mesa',
            name='id_gato',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mesa',
            name='id_mesa',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
