# Generated by Django 5.1.3 on 2024-12-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesa_app', '0003_remove_mesa_codigo_mesa_id_gato_mesa_id_mesa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='id_mesa',
        ),
        migrations.AddField(
            model_name='mesa',
            name='codigo',
            field=models.CharField(default=1, max_length=6, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
