# Generated by Django 5.1.3 on 2024-12-03 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesa_app', '0004_remove_mesa_id_mesa_mesa_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesa',
            old_name='codigo',
            new_name='id_mesa',
        ),
    ]
