# Generated by Django 5.1.3 on 2024-11-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('proveedor', models.CharField(max_length=100)),
                ('cantidad', models.CharField(max_length=100)),
                ('peso', models.CharField(max_length=100)),
                ('tamaño_empaque', models.CharField(max_length=100)),
                ('costo', models.CharField(max_length=255)),
            ],
        ),
    ]
