# Generated by Django 5.1.3 on 2024-11-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta_app', '0002_remove_venta_creditos_remove_venta_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='id_cliente',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='id_empleado',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='id_producto',
            field=models.IntegerField(null=True),
        ),
    ]
