# Generated by Django 5.1.3 on 2024-12-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta_app', '0003_venta_fecha_venta_venta_id_cliente_venta_id_empleado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='id_gato',
            field=models.IntegerField(null=True),
        ),
    ]
