# Generated by Django 5.1.3 on 2024-11-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='hora',
            field=models.CharField(max_length=12),
        ),
    ]
