# Generated by Django 5.1.3 on 2024-11-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_app', '0002_alter_orden_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='id_cliente',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='id_empleado',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='id_mesa',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='id_producto',
            field=models.IntegerField(null=True),
        ),
    ]
