# Generated by Django 5.1.3 on 2024-12-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_app', '0003_orden_id_cliente_orden_id_empleado_orden_id_mesa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='id_gato',
            field=models.IntegerField(null=True),
        ),
    ]
