# Generated by Django 5.1.3 on 2024-11-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gato_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gato',
            name='codigo',
            field=models.IntegerField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
