# Generated by Django 5.1.3 on 2024-11-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gato_app', '0002_alter_gato_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gato',
            name='codigo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
