# Generated by Django 5.1.3 on 2024-12-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gato_app', '0003_alter_gato_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gato',
            name='id_orden',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gato',
            name='id_venta',
            field=models.IntegerField(null=True),
        ),
    ]
