# Generated by Django 5.1.3 on 2024-12-03 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gato_app', '0004_gato_id_orden_gato_id_venta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gato',
            old_name='codigo',
            new_name='id_gato',
        ),
    ]
